spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:
  data:
    redis:
      host: 127.0.0.1
      port: 6379
  h2:
    console:
      enabled: true
mybatis:
  type-aliases-package: com.example.leaderboard.entity
